services:
  #database section
  tripdb:
    container_name: tripdb
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password@123
    ports:
      - "1435:1433"
    volumes:
      - tripdb_data:/var/opt/mssql

  paymentdb:
    container_name: paymentdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password@123
      - POSTGRES_DB=swiftridedb
    ports:
      - "5433:5432"
    volumes:
      - paymentdb_data:/var/lib/postgresql

  matchingdb:
    container_name: matchingdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Password@123
    ports:
      - "27017:27017"
    volumes:
      - matchingdb_data:/data/db

  #database ui section
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@swiftride.com
      - PGADMIN_DEFAULT_PASSWORD=Password@123
    ports:
      - "5051:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  mongo-express:
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://root:Password%40123@matchingdb:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH=false
    ports:
      - "8081:8081"

  #infrastructure section
  rabbitmq:
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  portainer:
    container_name: portainer
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data


  #microservice section
  payment.api:
    container_name: payment.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ConnectionStrings__DefaultConnection=Host=paymentdb;Port=5432;Database=swiftridedb;Username=postgres;Password=Password@123
      - EventBusSettings__HostAddress=rabbitmq
      - EventBusSettings__Port=5672
      - EventBusSettings__UserName=guest
      - EventBusSettings__Password=guest
      - OpenTelemetry__ServiceName=Payment.API
      - OpenTelemetry__OtlpEndpoint=http://jaeger:4317
    ports:
      - "6003:5000"
    restart: on-failure
    depends_on:
      - paymentdb
      - rabbitmq
      - jaeger

  matching.api:
    container_name: matching.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Kestrel Endpoints (Port 5000: HTTP/1.1 REST, Port 5001: HTTP/2 gRPC)
      - Kestrel__Endpoints__HttpRest__Url=http://+:5001
      - Kestrel__Endpoints__GrpcEndpoint__Url=http://+:5002
      # MongoDB Settings
      - MongoDbSettings__ConnectionString=mongodb://root:Password%40123@matchingdb:27017/?authSource=admin
      - MongoDbSettings__DatabaseName=matchingdb
      # EventBus / RabbitMQ Settings
      - EventBusSettings__HostAddress=rabbitmq
      - EventBusSettings__Port=5672
      - EventBusSettings__UserName=guest
      - EventBusSettings__Password=guest
      # OpenTelemetry / Jaeger Settings
      - OpenTelemetry__ServiceName=Matching.API
      - OpenTelemetry__OtlpEndpoint=http://jaeger:4317
    ports:
      - "6001:5001"
      - "6002:5002"
    depends_on:
      - matchingdb
      - rabbitmq
      - jaeger
