<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Usecases\Payments\Commands\" />
    <Folder Include="Usecases\Payments\Events\" />
    <Folder Include="Usecases\Payments\Queries\" />
  </ItemGroup>

</Project>
